#!/usr/bin/env bash
#that configures a new Ubuntu machine

apt-get update -y
apt-get install -y nginx

mkdir -p /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html

printf %s "server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root   /etc/nginx/html;
	index  index.html index.html;
}
" > /etc/nginx/sites-available/default

service restart nginx
